import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FooterLayout } from "./layout/footer/layout-footer";
import { HeaderLayout } from "./layout/header/layout-header";
import { MainLayout } from "./layout/main/layout-main";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`flex flex-col items-center justify-center  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderLayout />
        <MainLayout>
          {children}
        </MainLayout>
        <FooterLayout />
      </body>
    </html>
  );
}
